# Generated by Django 3.0.5 on 2020-05-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
