# Generated by Django 3.0.6 on 2020-05-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='image_file',
            field=models.ImageField(default=1, upload_to='event_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
