# Generated by Django 3.0.6 on 2020-05-09 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_event_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
    ]
