# Generated by Django 3.0.6 on 2020-05-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20200510_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
