# Generated by Django 3.0.6 on 2020-05-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_event_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
